---
title: "A Layered Grammar of Graphics"
author: "He Jiang"
topic: "03"
layout: post
root: ../../../
---

How does having a grammar help with creating charts?

For me, who has been having hard time creating beautiful plots in R, having a grammer really helps. First of all, it provides a structure that I can follow. By reading through the paper, I have learned there are 5 components in gglot2: data and aesthetic mappings, geometric objects, scales and coordinate system, faceting, and statistical transformations. So, from now on, I will remember to go over those 5 components everytime I create a plot, and think which ones I need, and how to make the plot tells what I want to know. 

Secondly, having a grammer breaks a big/complicated programming problem into small/tangible building blocks. After I remember the big picture, I only need to know how to code inside of each component. It is much easier to tackle than a long chunck of code. Last but not least, it is eaiser to make some changes in the code, especially if only certain components need the changes, which also benefits someone who is proof reading trying to reproduce. 


